import '../../public/assets/vendor/bootstrap/css/bootstrap.min.css'
import '../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css'
import '../../public/assets/vendor/boxicons/css/boxicons.min.css'
import '../../public/assets/vendor/quill/quill.snow.css'
import '../../public/assets/vendor/quill/quill.bubble.css'
import '../../public/assets/vendor/remixicon/remixicon.css'
import '../../public/assets/vendor/simple-datatables/style.css'
import '../../public/assets/css/style.css'
import './globals.css'

import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
//👇 Import Open Sans font
// import {NamedImport1, NamedImport2, NamedImport3,......} from 'somelibrary/location';
import { Open_Sans,Poppins,Nunito} from 'next/font/google'

//👇 Configure our font object
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ["400", "500", "600", "700", "800", "900"],
})

const nunito = Nunito({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.className} ${nunito.className} ${poppins.className}`}> 
        {children}
      </body>
    </html>
  )
}
